[window]
opacity = 0.94
startup_mode = "Maximized"
padding = { x = 16, y = 16 }
decorations_theme_variant = "dark"

[font]
normal = { family = "HackGen35 Console NF", style = "Regular" }

[colors]
transparent_background_colors = true
